apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application-project
  namespace: argocd
spec:
  description: This is the application project to cluster-k8s-local
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'