apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/allanrolli/kubernetes-argo-repo
      revision: HEAD
      directories:
      - path: cluster-k8s-local/applications/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: application-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/allanrolli/kubernetes-argo-repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc